/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class MenuAdminVista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdminVista.class.getName());
    private controlador.ControladorMenuPrincipal controlador;

    /**
     * Creates new form MenuAdminVista
     */
    public MenuAdminVista() {
        initComponents();
        controlador = new controlador.ControladorMenuPrincipal(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGestionTorneo = new javax.swing.JButton();
        btnGestionEquipos = new javax.swing.JButton();
        btnGestionJugadores = new javax.swing.JButton();
        btnGestionEntrenadores = new javax.swing.JButton();
        btnGestionInscripciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        btnAsignacionJugadores = new javax.swing.JButton();
        btnGestionRondas = new javax.swing.JButton();
        btnRegistroPartidos = new javax.swing.JButton();
        btnHGestionArbitros = new javax.swing.JButton();
        btnGestionSedes = new javax.swing.JButton();
        btnPatrocinadores = new javax.swing.JButton();
        btnConsultaTorneo = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGestionTorneo.setText("5.Gestion Torneo");

        btnGestionEquipos.setText("6.Gestion Equipos ");
        btnGestionEquipos.addActionListener(this::btnGestionEquiposActionPerformed);

        btnGestionJugadores.setText("7.Gestion Jugadores");
        btnGestionJugadores.addActionListener(this::btnGestionJugadoresActionPerformed);

        btnGestionEntrenadores.setText("1.Gestion Entrenadores");
        btnGestionEntrenadores.addActionListener(this::btnGestionEntrenadoresActionPerformed);

        btnGestionInscripciones.setText("9.Gestion Inscripciones");
        btnGestionInscripciones.addActionListener(this::btnGestionInscripcionesActionPerformed);

        jLabel1.setText("MENU GESTIÓN");

        jButton6.setText("Regresar ");

        btnAsignacionJugadores.setText("10.AsignacionJugadores");

        btnGestionRondas.setText("8.Gestion Rondas");

        btnRegistroPartidos.setText("11.Registro Partidos");

        btnHGestionArbitros.setText("2.Gestion Arbitros");

        btnGestionSedes.setText("3.GestionSedes");

        btnPatrocinadores.setText("4.GestionPatrocinadores");

        btnConsultaTorneo.setText("12.ConsultaTorneo");

        btnReporte.setText("REPORTE TORNEOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGestionTorneo)
                            .addComponent(btnGestionEquipos)
                            .addComponent(btnGestionJugadores)
                            .addComponent(btnRegistroPartidos)
                            .addComponent(btnHGestionArbitros)
                            .addComponent(btnPatrocinadores))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAsignacionJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGestionRondas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGestionEntrenadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGestionInscripciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGestionSedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultaTorneo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addComponent(btnReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionTorneo)
                    .addComponent(btnAsignacionJugadores))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionEquipos)
                    .addComponent(btnGestionRondas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionJugadores)
                    .addComponent(btnGestionEntrenadores))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistroPartidos)
                    .addComponent(btnGestionInscripciones))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHGestionArbitros)
                    .addComponent(btnGestionSedes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPatrocinadores)
                    .addComponent(btnConsultaTorneo))
                .addGap(29, 29, 29)
                .addComponent(btnReporte)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEquiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionEquiposActionPerformed

    private void btnGestionJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionJugadoresActionPerformed

    private void btnGestionEntrenadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEntrenadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionEntrenadoresActionPerformed

    private void btnGestionInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionInscripcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionInscripcionesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignacionJugadores;
    private javax.swing.JButton btnConsultaTorneo;
    private javax.swing.JButton btnGestionEntrenadores;
    private javax.swing.JButton btnGestionEquipos;
    private javax.swing.JButton btnGestionInscripciones;
    private javax.swing.JButton btnGestionJugadores;
    private javax.swing.JButton btnGestionRondas;
    private javax.swing.JButton btnGestionSedes;
    private javax.swing.JButton btnGestionTorneo;
    private javax.swing.JButton btnHGestionArbitros;
    private javax.swing.JButton btnPatrocinadores;
    private javax.swing.JButton btnRegistroPartidos;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnGestionTorneo() {
        return btnGestionTorneo;
    }

    public javax.swing.JButton getBtnGestionEquipos() {
        return btnGestionEquipos;
    }

    public javax.swing.JButton getBtnGestionJugadores() {
        return btnGestionJugadores;
    }

    public javax.swing.JButton getBtnGestionEntrenadores() {
        return btnGestionEntrenadores;
    }

    public javax.swing.JButton getBtnGestionInscripciones() {
        return btnGestionInscripciones;
    }

    public javax.swing.JButton getBtnAsignacionJugadores() {
        return btnAsignacionJugadores;
    }

    public javax.swing.JButton getBtnGestionRondas() {
        return btnGestionRondas;
    }

    public javax.swing.JButton getBtnRegistroPartidos() {
        return btnRegistroPartidos;
    }

    public javax.swing.JButton getBtnHGestionArbitros() {
        return btnHGestionArbitros;
    }

    public javax.swing.JButton getBtnGestionSedes() {
        return btnGestionSedes;
    }

    public javax.swing.JButton getBtnPatrocinadores() {
        return btnPatrocinadores;
    }

    public javax.swing.JButton getBtnConsultaTorneo() {
        return btnConsultaTorneo;
    }

    public javax.swing.JButton getBtnRegresar() {
        return jButton6;
    }

    public javax.swing.JButton getBtnReporte() {
        return btnReporte;
    }
}
